#!/bin/csh -xef

cd $MIR

# Create the library directory

if ( ! -d $MIR/inc ) mkdir $MIR/inc
if ( ! -d $MIR/lib ) mkdir $MIR/lib
if ( ! -d $MIR/lib/darwin ) mkdir $MIR/lib/darwin

# Retrieve the distribution and untar it.

wget -O rpfits.tar.gz ftp://ftp.atnf.csiro.au/pub/software/rpfits/rpfits.tar.gz
gunzip rpfits.tar.gz
tar -xvf rpfits.tar
find rpfits -exec chmod +rw {} \;

# Make a directory to hold the darwin code

cd rpfits/code
cp rpfits.inc $MIR/inc
if (! -d darwin ) mkdir darwin
chmod u+rw darwin
cp sun4sol/cvt_ieee.f darwin
chmod u+rw darwin/*
cp linux/atio.f darwin
chmod u+rw darwin/*

# Compile and make a library

g77 -c *.f darwin/*.f
ar cr $MIR/lib/darwin/librpfits.a *.o
ranlib $MIR/lib/darwin/librpfits.a
