#-----------------------------------------------------------------------------
# GNUmakefile used to check-out special Miriad doc files.
#
# Original: 2007/11/28, Mark Calabretta, ATNF
# $Id: GNUmakefile,v 1.1.1.1 2008/02/15 05:56:50 mirmgr Exp $
#-----------------------------------------------------------------------------
# Get common makefile variables and rules (defines everything needed here).
include $(MIR)/GNUmakedefs
