\bodytext{background=../hmiriad.gif}
\newcommand{\task}[1]{\href{../doc/#1.html}{#1}}
\newcommand{\unix}[1]{\href{/cgi-bin/miriad/mirman.pl?topic=#1}{#1}}
\newcommand{\miriad}{{\it Miriad}}
\newcommand{\aips}{AIPS}
\newcommand{\MM}[1]{{\it #1}}
\newcommand{\TT}[2]{{#1 by #2}}
\newcommand{\degrees}{\ degrees}
\newcommand{\kms}{km/s}
\newcommand{\radm}{rad/m/m}
\newcommand{\newchapter}{\null}
\newcommand{\lookat}{See}
\newcommand{\elll}{l}
\newcommand{\ssigma}{sigma}
