#!/bin/csh -f

# Look for the the libraries required for command line editting within the miriad shell.

set llib = `mirfind readline`
set tlib = `mirfind termcap`
set nlib = `mirfind ncurses`

if ( "$llib" == "" ) then
  echo "### Failed to find readline library when building readline-Miriad"
  exit
endif
if ( "$tlib" == "" && "$nlib" == "" ) then
  echo "### Failed to find both termcap and ncurses library when building readline-Miriad"
  exit
endif

rm -f miriad

if ( "$tlib" != "" ) then
  cc -o miriad -DREADLINE $MIR/tools/miriad.c -L$llib -lreadline -L$tlib -ltermcap
else
  cc -o miriad -DREADLINE $MIR/tools/miriad.c -L$llib -lreadline -L$nlib -lncurses
endif

if ( -x miriad ) then
  mv miriad $MIRBIN
else
  echo "### Failed to compile/link readline-Miriad"
endif
