#!/bin/csh -f

# Look for the readline library.

set llib = `mirfind readline`
set tlib = `mirfind termcap`
set nlib = `mirfind ncurses`

if ( "$llib" == "" ) then
  echo "### Failed to find readline library when building readline-Miriad"
  exit
endif
if ( "$tlib" == "" && "$nlib" == "" ) then
  echo "### Failed to find either termcap or ncurses library when building readline-Miriad"
  exit
endif

rm -f miriad

if ( "$llib" != "" ) then
  if ( "$tlib" != "" ) then
    cc -o miriad -DREADLINE $MIR/tools/miriad.c -L$llib -lreadline -L$tlib -ltermcap
  else
    cc -o miriad -DREADLINE $MIR/tools/miriad.c -L$llib -lreadline -L$nlib -lncurses
  endif
  if ( -x miriad ) then
    mv miriad $MIRBIN
  else
    echo "### Failed to compile/link readline-Miriad"
  endif
else
  echo "### Failed to find the readline library when building readline-Miriad"
endif

#rm -f ercmd
#cc -o ercmd ercmd.c
#if ( -x ercmd ) then
#  mv ercmd $MIRBIN
#else
#  echo "### Failed to build ercmd"
#endif
