#!/bin/csh -f

# Look for the readline library.

set lib = `mirfind readline`

rm -f miriad

if ( "$lib" != "" ) then
  cc -o miriad -DREADLINE $MIR/tools/miriad.c -L$lib -lreadline -ltermcap
  if ( -x miriad ) then
    mv miriad $MIRBIN
  else
    echo "### Failed to compile/link readline-Miriad"
  endif
else
  echo "### Failed to find the readline library when building readline-Miriad"
endif

#rm -f ercmd
#cc -o ercmd ercmd.c
#if ( -x ercmd ) then
#  mv ercmd $MIRBIN
#else
#  echo "### Failed to build ercmd"
#endif
