#!/bin/csh -f

set lib = `mirfind X11` 
set inc = `mirfind -i X11` 

cc -O -o sxmtv.exe -I../xmtv -I$inc -I$inc/X11 \
   colors.c comm.c cursor.c image.c init.c screen.c selectpt.c sxmtv.c \
	-L$lib -lX11 -lm

if ( -e sxmtv.exe ) then
  mv sxmtv.exe $MIRBIN
else
  echo "### Failed to build sxmtv"
endif
cp ../xmtv/xmtv.csh $MIRBIN/xmtv
chmod +x $MIRBIN/xmtv
